[package]
name = "midix"
version = "2.0.0"
edition = "2021"
authors = ["dsgallups <dsgallups@protonmail.com>"]
description = "Human-readable MIDI decoder and encoder for real-time MIDI events"
repository = "https://github.com/dsgallups/midix"
documentation = "https://docs.rs/midix"
readme = "README.md"
keywords = ["midi", "audio", "parser"]
categories = ["multimedia::audio", "multimedia::encoding", "multimedia"]
license = "MIT OR Apache-2.0"


[features]
bevy = ["dep:bevy"]

[dependencies]
bevy = { version = "0.15", optional = true, default-features = false }

[dev-dependencies]
pretty_assertions = { default-features = false, features = [
    "alloc",
], version = "1.4.1" }
