[package]
name = "midix"
version = "1.0.0"
edition = "2021"
authors = ["dsgallups <dsgallups@protonmail.com>"]
description = "Human-readable MIDI decoder and encoder for real-time MIDI events"
repository = "https://github.com/dsgallups/midix"
documentation = "https://docs.rs/midix"
readme = "README.md"
keywords = ["midi", "audio", "parser"]
categories = ["multimedia::audio", "multimedia::encoding", "multimedia"]
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "2.0.9"

[features]
nightly = []

[dev-dependencies]
pretty_assertions = { default-features = false, features = [
    "alloc",
], version = "1.4.1" }
