[package]
name = "midix"
version = "0.0.1"
edition = "2021"
authors = ["negamartin", "dsgallups <dsgallups@protonmail.com>"]
description = "Fast MIDI decoder and encoder both for .mid files and real-time MIDI events"
repository = "https://github.com/dsgallups/midix"
documentation = "https://docs.rs/midix"
readme = "README.md"
keywords = ["midi", "no_std", "audio", "parser"]
categories = ["multimedia::audio", "multimedia::encoding", "multimedia"]
license = "MIT OR Apache-2.0"


[dependencies]
midly = "0.5.3"
rayon = { version = "1", optional = true }

[dev-dependencies]
pretty_assertions = { default-features = false, features = [
    "alloc",
], version = "1.4.1" }
