[package]
name = "midix"
version = "2.0.0"
edition = "2024"
authors = ["dsgallups <dsgallups@protonmail.com>"]
description = "Human-readable MIDI decoder and encoder for real-time MIDI events"
repository = "https://github.com/dsgallups/midix"
documentation = "https://docs.rs/midix"
readme = "README.md"
keywords = ["midi", "audio", "parser"]
categories = ["multimedia::audio", "multimedia::encoding", "multimedia"]
license = "MIT OR Apache-2.0"


[features]
bevy = ["dep:bevy"]
synth = ["dep:rustysynth"]
debug = ["bevy", "synth"]

[dependencies]
bevy = { version = "0.15", optional = true, default-features = false }
rustysynth = { version = "1.3.3", optional = true }

[dev-dependencies]
pretty_assertions = { default-features = false, features = [
    "alloc",
], version = "1.4.1" }
tinyaudio = "1.0.0"
itertools = "0.13.0"
