[package]
name = "bevy_midix"
version = "3.0.0-rc1"
authors = ["dsgallups <dsgallups@protonmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dsgallups/midix"
documentation = "https://docs.rs/bevy_midix"
description = "Send/receive MIDI data in bevy with midix."
keywords = ["gamedev", "bevy", "midi", "encoding", "control"]
categories = ["game-development", "game-engines", "encoding"]
exclude = ["assets/*"]


[dependencies]
midir = "0.10"
crossbeam-channel = "0.5.15"
midix = { version = "3.0.0-rc1", features = ["bevy"], path = "../midix" }
midix_synth = { version = "0.0.1-rc1", path = "../midix_synth" }
thiserror = "2.0"

[dev-dependencies]
strum = { version = "0.27", features = ["derive"] }

[dependencies.bevy]
version = "0.16.0-rc.3"
default-features = false
features = ["multi_threaded", "bevy_asset", "std", "async_executor"]

[dev-dependencies.bevy]
version = "0.16.0-rc.3"
default-features = true
