[package]
name = "bevy_midix"
version = "3.0.0-rc1"
authors = ["dsgallups <dsgallups@protonmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dsgallups/midix"
documentation = "https://docs.rs/bevy_midix"
description = "Send/receive MIDI data in bevy with midix."
keywords = ["gamedev", "bevy", "midi", "encoding", "control"]
categories = ["game-development", "game-engines", "encoding"]
exclude = ["assets/*"]


[dependencies]
midir = "0.10"
crossbeam-channel = "0.5.8"
midix = { version = "3.0.0-rc1", features = ["bevy"], path = "../midix" }
midix_synth = { version = "0.0.1-rc1", path = "../midix_synth" }
thiserror = "2.0.9"

[dev-dependencies]
bevy_egui = { version = "0.31.1", features = ["immutable_ctx"] }
strum = { version = "0.26", features = ["derive"] }

[dependencies.bevy]
version = "0.15"
default-features = false
features = ["multi_threaded", "bevy_asset"]

[dev-dependencies.bevy]
version = "0.15"
default-features = true
